### ISSUE TITLE
gen12_igd.rom和gen12_gop.rom都支持10代核显uhd630吗

### ISSUE THREAD

**Issue by kimown** [gangqizai/igd#2]
看README.md描述，这2个文件支持范围不一样

**Comment by cmd2001** [comment]
`gen12_igd.rom`主要包含OVMF(虚拟机UEFI)的补丁，按理说是6-14代通用的
`gen12_gop.rom`可理解为UEFI下的显卡驱动，**平台相关**，最好用UBU从自己主板或同代其他主板的BIOS中提取

**Comment by TSEtq** [comment]
> `gen12_igd.rom`主要包含OVMF(虚拟机UEFI)的补丁，按理说是6-14代通用的 `gen12_gop.rom`可理解为UEFI下的显卡驱动，**平台相关**，最好用UBU从自己主板或同代其他主板的BIOS中提取

gop.rom不是开机引导画面的吗？  igd.rom才是显卡关键的文件

**Comment by cmd2001** [comment]
> > `gen12_igd.rom`主要包含OVMF(虚拟机UEFI)的补丁，按理说是6-14代通用的 `gen12_gop.rom`可理解为UEFI下的显卡驱动，**平台相关**，最好用UBU从自己主板或同代其他主板的BIOS中提取
> 
> gop.rom不是开机引导画面的吗？ igd.rom才是显卡关键的文件

`gop`是`uefi`下的核显驱动，由设备制造商固件提取。理论上只要虚拟机`uefi`固件(在这里是`ovmf`)可以识别`gop`并正确加载，就能在`uefi`阶段点亮屏幕。
可惜虚拟机的固件`ovmf`不能直接利用Intel提供的`gop`，所以需要打补丁，也就是`igd.rom`。
具体你说的开机引导画面，我们这里要实现的就是显示开机引导画面。实际上系统核显驱动加载后，`gop`驱动将失去作用。
要实验的话，可以用未经修改的`ovmf`进行直通，当系统内核显驱动加载后，屏幕照样会点亮。

**Comment by kimown** [comment]
@cmd2001 
`gen12_gop.rom` 是ubu提取的`IntelGopDriver.efi`, 通过efirom.exe转rom生成的吗

**Comment by cmd2001** [comment]
是的

**Comment by kimown** [comment]
10代核显是支持的，感谢大佬。

**Comment by joepeak** [comment]
gen12_igd.rom 是怎么生成的呢
