### ISSUE TITLE
极摩客G3 n100迷你主机，首次启动win11花屏

### ISSUE THREAD

**Issue by sonicno1** [gangqizai/igd#8]
极摩客G3 N100迷你主机hdmi输出，首次启动win11花屏，再次启动正常，每次得重新启动一次。

**Comment by ousui** [comment]
零刻没G3 吧，n100 是 eq12
https://github.com/ousui/igd/releases/tag/roms

**Comment by sonicno1** [comment]
抱歉，说错了，是极摩客G3。

**Comment by sonicno1** [comment]
感谢作者的更新

**Comment by sonicno1** [comment]
![Uploading 16976950579632096752277411592277.jpg…]()

**Comment by sonicno1** [comment]
对声卡也是有问题，播放视频不知道什么情况直接静音了，必须整个pve系统关机后再开机才有声音。

**Comment by sonicno1** [comment]
声卡机器自带的usb声卡，应该与这个模块没关系。

**Comment by hehh2001** [comment]
大佬能做一个i3-N305 的吗？用这个也是第一次花屏，很麻烦！！再次感谢你的工作！！！！！！！！！
